service: wetalkin-python-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-2

package:
  individually: false
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**

functions:
  get_joke:
    handler: handler.get_joke
    events:
      - http:
          path: joke
          method: get

plugins:
  - serverless-python-requirements
